# Generated by Django 2.2.6 on 2019-11-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_location',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
