# Generated by Django 2.2.6 on 2019-10-31 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_PlaidID', models.CharField(editable=False, max_length=128, null=True, unique=True)),
                ('account_name', models.CharField(max_length=128)),
                ('account_type', models.CharField(max_length=128)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_plaidID', models.CharField(editable=False, max_length=128, null=True, unique=True)),
                ('transaction_name', models.CharField(max_length=128)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_location', models.CharField(max_length=256)),
                ('transaction_date', models.DateField()),
                ('account_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mango.Account')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
